### **NUMPY BASICS** 🙂

In [5]:
import numpy as np

In [6]:
my_list = [1,3,5,6,7,8]

### **Converting a List into an Array**

---











In [7]:
arr= np.array(my_list)
arr

array([1, 3, 5, 6, 7, 8])

In [8]:
arr2 =np.array([[1,2,3,4], [9,8,7,6]])

### **Array Properties**

---



In [9]:
arr2.shape


(2, 4)

In [10]:
arr2.ndim


2

In [11]:
arr2.size

8

In [12]:
arr2.dtype

dtype('int64')

### **Array Operations**

---



In [13]:
arr2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

### **Accessing Rows**

---



In [14]:
arr2[0]

array([1, 2, 3, 4])

In [15]:
#First Element
arr2[0,0]

1

In [16]:
arr2[1,2]

7

In [17]:
arr2[1,1:]

array([8, 7, 6])

In [18]:
arr2[1,0:1]

array([9])

###**Accessing Columns**



---



In [19]:
arr2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [20]:
###Getting the last Column
arr2[:,3]

array([4, 6])

In [21]:
###Getting the first Column
arr2[:, 0]

array([1, 9])

### **Initializing Arrays**

---



In [22]:
### Single Vector
a= np.zeros(2)
a

array([0., 0.])

In [23]:
b= np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [24]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
### 3D Arrays
d = np.zeros((3,5,4))
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
e = np.ones((2,3))
e

array([[1., 1., 1.],
       [1., 1., 1.]])

### **Reshaping Arrays**

---



In [27]:
l = np.array([[1,2,3,4], [8,9,10,11]])
l

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [28]:
l.reshape((2,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 8,  9],
        [10, 11]]])

In [29]:
k = l.reshape(1,8)
k


array([[ 1,  2,  3,  4,  8,  9, 10, 11]])

In [30]:
l

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

### **Mathematics**

---



In [31]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [32]:
array1*2


array([2, 4, 6, 8])

In [33]:
array1+3

array([4, 5, 6, 7])

In [34]:
array1 /255


array([0.00392157, 0.00784314, 0.01176471, 0.01568627])

In [35]:
np.cos(a)

array([1., 1.])

In [36]:
np.sin(a)

array([0., 0.])

### **Linear Algebra**

---



In [37]:
 s = np.ones((2,3))
 print(s)

d = np.full((3,2), 2)
print(d)

np.matmul(s,d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [38]:
### Creating an Identity matrix of size 4*4 and Finding the Determinent
f = np.identity(4)
np.linalg.det(f)

1.0

### **Statistics**

---



In [39]:
g = np.array([[1,2,3,4], [5,6,7,8]])
g

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.min(g)

1

In [41]:
np.max(g)

8

In [42]:
np.median(g)

4.5

In [43]:
np.sum(g)

36

In [44]:
###Combining Arrays or Stacking Arrays

V1 = [1,3,5,7,9]
V2= [2,4,6,8,10]

np.vstack((V1,V2))

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [45]:
### Horizontal Stacking

e1 = np.ones((2,4))
e2= np.zeros((2,2))

np.hstack((e1,e2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### **Loading data from a file**

---



In [46]:
path = "/content/drive/MyDrive/New Text Document.txt"

In [49]:
filedata = np.genfromtxt(path, delimiter = ",")
filedata

array([1.5000e+01, 1.6000e+01, 7.9000e+01, 4.5000e+01, 1.2120e+03,
       1.2150e+03, 5.6000e+01, 6.5400e+02, 7.9000e+01, 6.5200e+02,
       3.3000e+01, 2.4600e+02,        nan, 5.4000e+01, 1.3200e+02,
       1.0000e+00, 4.6800e+02, 3.5121e+04])

In [61]:
## Data is in float, we can change that to int as well
filedata = filedata.astype('int32')

In [62]:
filedata

array([         15,          16,          79,          45,        1212,
              1215,          56,         654,          79,         652,
                33,         246, -2147483648,          54,         132,
                 1,         468,       35121], dtype=int32)

In [66]:
### Print particular values with help of index
filedata[filedata> 100]

array([ 1212,  1215,   654,   652,   246,   132,   468, 35121],
      dtype=int32)

In [69]:
### Reversing an array using Numpy

cv = np.array([90,89,87,86,85,84])

In [70]:
np.flip(cv)

array([84, 85, 86, 87, 89, 90])

### **Flattening an Array**

---



In [72]:
xc = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [81]:
flattened = xc.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
### When you use flatten, changes to your new array won’t change the parent array.